server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=userdb;trustServerCertificate=true;sendTimeAsDateTime=false
    username: simon
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # HikariCP 連接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: UserHikariPool-dev
      # SQL Server 特定配置
      data-source-properties:
        applicationName: user-service-dev
        lockTimeout: 15000
        queryTimeout: 15
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
        '[jdbc.batch_size]': 50
        '[jdbc.fetch_size]': 50
        '[order_updates]': true
        '[batch_versioned_data]': true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 開發環境安全配置
security:
  jwt:
    secret: dev_secret_key_123
    expiration: 86400000  # 24小時

# 開發環境日誌配置
logging:
  level:
    '[com.example.userapp]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.hibernate]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
