server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://test-db:5432/userdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true
  security:
    jwt:
      secret: test_secret_key_456
      expiration: 86400000  # 24小時

eureka:
  client:
    serviceUrl:
      defaultZone: http://test-eureka:8761/eureka/
  instance:
    prefer-ip-address: true

# 測試環境日誌配置
logging:
  level:
    '[com.example.userapp]': INFO
    '[org.springframework.web]': INFO
    '[org.springframework.security]': INFO
    '[org.hibernate]': INFO

# 基礎監控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
