server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false
  # 安全配置
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms

# JWT 配置
jwt:
  secret: ${JWT_SECRET}
  expiration: 43200000  # 12小時

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URLS}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# 生產環境日誌配置
logging:
  level:
    '[com.example.userapp]': WARN
    '[org.springframework.web]': WARN
    '[org.springframework.security]': WARN
  file:
    name: /var/log/user-service/user.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 監控配置
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
